[llvm]
enabled = true
optimize = true
static-libstdcpp = true
ninja = true
targets = "X86"

[build]
build = "x86_64-unknown-linux-gnu"
host = ["x86_64-unknown-linux-musl"]
target = ["x86_64-unknown-linux-musl"]
#cargo = "/usr/bin/cargo"
#rustc = "/usr/bin/rustc"
docs = false
#fast-submodules = false
extended = true
# Verbosity level: 0 == not verbose, 1 == verbose, 2 == very verbose
verbose = 0
cargo-native-static = true
low-priority = true
print-step-timings = true
tools = ["cargo", "rls", "rustfmt", "analysis", "src"]

[rust]
codegen-units = 0
use-jemalloc = false
# Whether or not `panic!`s generate backtraces (RUST_BACKTRACE)
#backtrace = true
# Whether to always use incremental compilation when building rustc
#incremental = false
channel = "stable"

[target.x86_64-unknown-linux-musl]
cc = "/usr/local/bin/x86_64-unknown-linux-musl-gcc"
cxx = "/usr/local/bin/x86_64-unknown-linux-musl-g++"
ar = "/usr/local/bin/x86_64-unknown-linux-musl-ar"
ranlib = "/usr/local/bin/x86_64-unknown-linux-musl-ranlib"
linker = "/usr/local/bin/x86_64-unknown-linux-musl-gcc"
crt-static = false

[target.x86_64-gentoo-linux-musl]
cc = "/usr/local/bin/x86_64-unknown-linux-musl-gcc"
cxx = "/usr/local/bin/x86_64-unknown-linux-musl-g++"
ar = "/usr/local/bin/x86_64-unknown-linux-musl-ar"
ranlib = "/usr/local/bin/x86_64-unknown-linux-musl-ranlib"
linker = "/usr/local/bin/x86_64-unknown-linux-musl-gcc"
crt-static = true
